# Generated by Django 4.1.7 on 2023-04-21 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('barcode_id', models.TextField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=255)),
                ('price', models.IntegerField(max_length=255)),
                ('categories', models.TextField(max_length=255)),
                ('item_image', models.ImageField(blank=True, default='default_item.jpg', upload_to='items')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default='default_profile.jpg', upload_to='profiles'),
        ),
    ]
