# Generated by Django 4.1.7 on 2023-04-21 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_cart', '0004_alter_store_item_image_alter_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default='default_profile.jpeg', upload_to='profiles'),
        ),
    ]
