# Generated by Django 4.1.2 on 2023-04-27 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_cart', '0006_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default='/profiles/default_profile.jpeg', upload_to='profiles'),
        ),
    ]
