# Generated by Django 4.1.2 on 2023-06-06 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_cart', '0009_cart_cart_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='store',
            name='item_image',
            field=models.ImageField(blank=True, default='/items/default_item.jpeg', upload_to='items'),
        ),
    ]
